title = "Sandwich"  # From Git
gitRepoUrl = "https://github.com/yourusername/sandwich" # From Git

gitSourceBranch = "main"
changelog = true
classOrder = [
	"Sandwich",
	"Stream",
	"Job",
	"Task",
]

[home]
enabled = true
includeReadme = false

[[home.features]]
title = "Event Management"
description = "Sandwich allows you to easily create, modify, and manage schedulers in your projects."
image = "/EventLoop.png"

[[home.features]]
title = "Extensible and Composable"
description = "Sandwich provides a variety of functions for inserting, removing, and replacing tasks within scheduled streams, making it easy to extend and compose event-driven logic in your applications."
image = "/PuzzlePieces.png"

[[home.features]]
title = "Lightweight and Efficient"
description = "Sandwich is a lightweight scheduler designed to minimize overhead and maximize efficiency, making it an ideal solution for managing jobs in your Roblox projects."
image = "/Lightweight.png"

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "/favicon.ico"

# From git:
organizationName = "SolarScuffle-Bot"
projectName = "Sandwich"
url = "https://solorscuffle-bot.github.io"
baseUrl = "/Sandwich/"
tagline = "Roblox's lightweight scheduler"

[navbar]
# hideableSidebar = true

[[navbar.items]]
href = "https://discord.gg/34wu9VXeyR"
label = "Discord"
position = "right"

[footer]
style = "dark"
copyright = "Copyright © 2023 SolarScuffle-Bot. Built with Moonwave and Docusaurus"

# [[footer.links]]
# title = "examples"

# [[footer.links.items]]
# label = "example"
# href = "https://example.com/"