title = "Sandwich"  # From Git
gitRepoUrl = "https://github.com/solarscuffle-bot/sandwich" # From Git

gitSourceBranch = "main"
changelog = true

[home]
enabled = true
includeReadme = false

[[home.features]]
title = "Extensible and Composable"
description = "Because all logic is separated from data, and data is split up into Tasks, Jobs, and Streams, your jobs and streams are extensible and composable right from the start!"
# image = "/PuzzlePieces.png"

[[home.features]]
title = "Task Scheduling"
description = "Sandwich allows you to easily define, order, and execute tasks in your experiences."
image = "/SandwichLogo.png"

[[home.features]]
title = "Lightweight and Efficient"
description = "Sandwich is a lightweight scheduler designed to minimize overhead and maximize efficiency, making it an ideal solution for managing jobs in your Roblox projects. It leverages the power of arrays and optimized data definitions to achieve this."
# image = "/Lightweight.png"

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "/favicon.ico"

# From git:
organizationName = "SolarScuffle-Bot"
projectName = "Sandwich"
url = "https://solorscuffle-bot.github.io"
baseUrl = "/Sandwich/"
tagline = "Roblox's lightweight scheduler"

[navbar]
# hideableSidebar = true

[footer]
style = "dark"
copyright = "Copyright © 2023 SolarScuffle-Bot. Built with Moonwave and Docusaurus"

# [[footer.links]]
# title = "examples"

# [[footer.links.items]]
# label = "example"
# href = "https://example.com/"