[package]
name = "solarscuffle-bot/sandwich"
version = "1.0.1"
registry = "https://github.com/UpliftGames/wally-index"
licence = "MIT"
authors = ["Sona"]

description = "A minimalistic, lightweight, performant scheduler for luau."

realm = "shared"

exclude = ["README.md"]

[dependencies]
